name: Cufy.org
title: Cufy Organization
email: info@cufy.org
description: >- # this means to ignore newlines until "baseurl:"
  Cufy is an non-profit open-source international organization focused on gathering
  variant kinds of programmers from beginners to professionals so members learn
  from another. Because Cufy is a nonprofit organization, the main target of Cufy
  members is friendship, experience and popularity.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: CufyOrg

markdown: kramdown

emails:
  cmail: info@cufy.org
  gmail: cufyorg@gmail.com

defaults:
  - scope:
      path: ""
    values:
      favicon: '/assets/ico/cufy.ico'
      title: 'Cufy Organization'

include:
  - pages
  - javadoc

github:
  is_project_page: true
  repository_url: https://github.com/cufyorg/cufyorg.github.io
  owner_url: https://github.com/cufyorg
  owner_name: Cufy
